name: Scheduled Jobs

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  attempt_booking:
    name: Attempt Booking
    runs-on: ubuntu-latest
    # REMOVED: "environment: sushi" (This prevents errors if the env doesn't exist)
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm
          cache-dependency-path: package-lock.json

      # This creates the file your bot reads
      - run: echo '${{ secrets.CYPRESS_ENV }}' > cypress.env.json

      - run: npm ci

      - run: npm test

      - uses: gautamkrishnar/keepalive-workflow@v1
