name: Scheduled Jobs

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  attempt_booking:
    name: Attempt Booking
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json

      - run: echo '${{ secrets.CYPRESS_ENV }}' > cypress.env.json

      - run: npm ci

      # FORCE CHROME TO RUN
      - run: npm test

      # --- CRITICAL STEP: SAVE SCREENSHOTS ---
      # This saves the picture of what the bot saw when it failed
      - uses: actions/upload-artifact@v4
        if: always()  # Run this even if the test failed!
        with:
          name: debug-screenshots
          path: cypress/screenshots
          retention-days: 1
